version: '3.4'

services:
  vortexl4d2manager:
    image: vortexl4d2manager
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3081:3081
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
